machines:
  - id: cabinet_1
    <<: *machine-base
    <<: *source-1
    CollectionDrivers.BatteryDriver.Strategies.BatteryTcpStrategy, CollectionDrivers.BatteryDriver:
      collectors:
      - CollectionDrivers.BatteryDriver.Collectors.ChannelData, CollectionDrivers.BatteryDriver
      - CollectionDrivers.BatteryDriver.Collectors.EquipmentAlarm, CollectionDrivers.BatteryDriver
      - CollectionDrivers.BatteryDriver.Collectors.CommandResult, CollectionDrivers.BatteryDriver
