machines:
  - id: stacker_1
    enabled: true
    type: CollectionDrivers.FinsDriver.FinsMachine, CollectionDrivers.FinsDriver
    strategy: CollectionDrivers.FinsDriver.Strategies.FinsStrategy, CollectionDrivers.FinsDriver
    handler: l99.driver.@base.Handler, base-driver

    CollectionDrivers.FinsDriver.FinsMachine, CollectionDrivers.FinsDriver:
      sweep_ms: 500

    CollectionDrivers.FinsDriver.Strategies.FinsStrategy, CollectionDrivers.FinsDriver:
      remote_ip: "192.168.250.1"
      port: 9600
      timeout_ms: 2000

      collectors:
        - name: slot_signals
          start_address: 100
          length: 280

        - name: scanner_signals
          start_address: 10
          length: 2
