machines:
  - id: cabinet_1
    <<: *machine-base
    <<: *source-1
    battery.driver.strategies.BatteryTcpStrategy, battery-driver:
      collectors:
      - battery.driver.collectors.ChannelData, battery-driver
      - battery.driver.collectors.EquipmentAlarm, battery-driver
      - battery.driver.collectors.CommandResult, battery-driver
